# Generated by Django 2.2.6 on 2019-11-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('score', models.FloatField(default=None, max_length=10)),
                ('words_frequency_image', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'companies',
            },
        ),
    ]
